# Generated by Django 4.2 on 2023-04-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Model_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_source_id', models.IntegerField(help_text='Unique part for source of waste', max_length=100)),
                ('waste_source_profile', models.CharField(help_text='Source of waste ex. House, restaurant, hotel, etc.', max_length=200)),
                ('food_name', models.CharField(help_text='Source of waste ex. House, restaurant, hotel, etc.', max_length=200)),
                ('food_quantity', models.IntegerField(help_text='Quantity of the food item', max_length=100)),
                ('food_price', models.DecimalField(decimal_places=2, default=9999.99, help_text='Cost of the food item', max_digits=9)),
                ('waste_date', models.DateTimeField(help_text='Date of waste disposal.')),
                ('waste_reason', models.CharField(help_text='Reason for disposing Waste.', max_length=200)),
                ('waste_quantity', models.IntegerField(help_text='Quantity of the food item', max_length=100)),
            ],
        ),
    ]
