# Generated by Django 4.2 on 2023-04-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_model_table',
            name='food_name',
            field=models.CharField(help_text='Name of Food ex. apple, bread, juice, etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='data_model_table',
            name='waste_source_id',
            field=models.IntegerField(help_text='Unique Code for source of waste', max_length=100),
        ),
    ]
