# Generated by Django 4.2 on 2023-05-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste_app', '0003_usermodel_alter_data_model_table_waste_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_model_table',
            name='food_quantity',
            field=models.IntegerField(help_text='Quantity of the food item'),
        ),
        migrations.AlterField(
            model_name='data_model_table',
            name='waste_quantity',
            field=models.IntegerField(help_text='Weight of food waste in kgs.'),
        ),
        migrations.AlterField(
            model_name='data_model_table',
            name='waste_source_id',
            field=models.IntegerField(help_text='Unique Code for source of waste'),
        ),
    ]
