# Generated by Django 4.2 on 2023-05-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste_app', '0009_bin_model_food_model_waste_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubbishbin_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_name', models.CharField(max_length=30)),
                ('bin_location', models.CharField(max_length=50)),
                ('bin_capacity', models.IntegerField()),
                ('bin_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Bin_Model',
        ),
        migrations.AddField(
            model_name='waste_model',
            name='bin',
            field=models.ManyToManyField(to='foodwaste_app.rubbishbin_model'),
        ),
    ]
