# Generated by Django 4.2 on 2023-05-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodwaste_app', '0010_rubbishbin_model_delete_bin_model_waste_model_bin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_model',
            old_name='fooditem_category',
            new_name='food_category',
        ),
        migrations.RenameField(
            model_name='food_model',
            old_name='fooditem_measurement',
            new_name='food_measurement',
        ),
        migrations.RenameField(
            model_name='food_model',
            old_name='fooditem_name',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='waste_model',
            old_name='employee',
            new_name='employeeid',
        ),
        migrations.RemoveField(
            model_name='food_model',
            name='fooditem_type',
        ),
        migrations.AddField(
            model_name='employee_model',
            name='emp_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food_model',
            name='food_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='food_model',
            name='food_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rubbishbin_model',
            name='bin_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='waste_model',
            name='waste_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rubbishbin_model',
            name='bin_location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rubbishbin_model',
            name='bin_status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='waste_model',
            name='dollar_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='waste_model',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='waste_model',
            name='waste_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='waste_model',
            name='waste_disposal_method',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='waste_model',
            name='waste_location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='waste_model',
            name='waste_reason',
            field=models.CharField(max_length=30),
        ),
    ]
